package com.home.expensetrack.datamigrate.mapper.Impl;

import java.util.Map;

public class Map2015TypeTo2024DebitSubAccounts {
    public static Map<String, String> map = Map.ofEntries(Map.entry("CASH - $","Other Expense"),
            Map.entry("CEFCU Checking A/c [D] - Check Payment","Housing Expenses"),
            Map.entry("Shell Charge Card","Travel Expense"),
            Map.entry("CEFCU Credit Card [D]","Other Expense"),
            Map.entry("CEFCU Debit Card [D] - Payment","Other Expense"),
            Map.entry("CEFCU Checking A/c [D] - Withdraw","CashAsset"),
            Map.entry("Lend Cash","Personal Loan"),
            Map.entry("CEFCU Checking A/c [D] - Check Deposit","CEFCU Checking - Dinesh"),
            Map.entry("CEFCU Checking A/c [D] - ACH Payment","Other Expense"),
            Map.entry("CEFCU Checking A/c [D] -> Savings A/c [D]","CEFCU Saving - Dinesh"),
            Map.entry("CEFCU Checking A/c [D] - ACH Deposit","CEFCU Checking - Dinesh"),
            Map.entry("Cash Received","CashAsset"),
            Map.entry("Bergner's Card [D]","Other Expense"),
            Map.entry("CEFCU Checking A/c [D] - Credit Card Check Payment","Vendor Bank"),
            Map.entry("JCPenney Card","Other Expense"),
            Map.entry("Paid for with CEFCU Credit Card","Other Expense"),
            Map.entry("Chase Credit Card","Other Expense"),
            Map.entry("Sears Charge Card","Other Expense"),
            Map.entry("Cash - INR","Other Expense"),
            Map.entry("CEFCU Checking A/c [D] - Credit Card ACH Payment","Vendor Bank"),
            Map.entry("Famous Baar / Macy's Card","Other Expense"),
            Map.entry("Online Payment - CEFCU","Other Expense"),
            Map.entry("CEFCU Checking A/c [D] - M2I Transfer","ICICI"),
            Map.entry("Kohl's Card [D] & [S]","Other Expense"),
            Map.entry("Providian CreditCard Deposit","Providian Card"),
            Map.entry("Mail In Rebate - Checks","CEFCU Checking - Dinesh"),
            Map.entry("Gift Card - Received","Gift Card"),
            Map.entry("Gift Card - Payment","Other Expense"),
            Map.entry("Refund","CashAsset"),
            Map.entry("CEFCU Debit Card [D] - Withdraw","CashAsset"),
            Map.entry("Sears Master Card","Other Expense"),
            Map.entry("Sam's Club Discover Card","Other Expense"),
            Map.entry("CEFCU Checking A/c [S] - Check Deposit","CEFCU Checking - Sebina"),
            Map.entry("CAT Health Insurance - Payment","Medical Expense"),
            Map.entry("CEFCU Saving A/c [S] -> Checking A/c [D]","CEFCU Checking - Dinesh"),
            Map.entry("CEFCU Saving A/c [S] - Check Deposit","CEFCU Saving - Sebina"),
            Map.entry("CEFCU Checking A/c [S] - ACH Deposit","CEFCU Checking - Sebina"),
            Map.entry("CEFCU Check Card [S] - Payment","Other Expense"),
            Map.entry("CEFCU Checking A/c [S] - Withdraw","CashAsset"),
            Map.entry("ICICI Res A/c - M2I Deposit","ICICI Ngl Joint"),
            Map.entry("CEFCU Saving A/c [S] - ACH Deposit","CEFCU Saving - Sebina"),
            Map.entry("CEFCU Saving A/c [D] - ACH Deposit","CEFCU Saving - Dinesh"),
            Map.entry("CEFCU Checking A/c [S] -> Savings A/c [S]","CEFCU Saving - Sebina"),
            Map.entry("CEFCU Savings A/c [D] -> Checking A/c [D]","CEFCU Checking - Dinesh"),
            Map.entry("Bergner's Card [S]","Other Expense"),
            Map.entry("SBI Remit Express Transfer","SBI"),
            Map.entry("CEFCU Saving A/c [D] - Check Deposit","CEFCU Saving - Dinesh"),
            Map.entry("Joint ICICI NGL Savings A/c","Other Expense"),
            Map.entry("CEFCU Checking A/c [S] -> Checking A/c [D]","CEFCU Checking - Dinesh"),
            Map.entry("CEFCU Checking A/c [D] - SBI Remit Express","SBI"),
            Map.entry("ICICI Res A/c - Credit","ICICI Ngl Joint"),
            Map.entry("CEFCU Saving A/c [S] -> Saving A/c [D]","CEFCU Saving - Dinesh"),
            Map.entry("Tambaram Project - Cash Payment","Other Expense"),
            Map.entry("Tambaram Project - Mama Cash Payment","Other Expense"),
            Map.entry("CEFCU Saving A/c [S] -> Santa Saver A/c [S]","CEFCU"),
            Map.entry("ICICI Res A/c - Tambaram Project Payment","Other Expense"),
            Map.entry("CEFCU Checking A/c [S] -> Savings A/c [D]","CEFCU Saving - Dinesh"),
            Map.entry("ICICI Res A/c - Withdraw","CashAsset"),
            Map.entry("SBI NRE A/c - Credit","SBI Kulithurai NRE"),
            Map.entry("Cash Received - Rs","CashAsset"),
            Map.entry("Tambaram Apt - Maintanence","Other Expense"),
            Map.entry("Tambaram Apt - Rent","CashAsset"),
            Map.entry("ICICI Res A/c - Tambaram Apt Maintanence","Other Expense"),
            Map.entry("SBI NRE A/c - Check Payment","Other Expense"),
            Map.entry("ICICI NRE A/c - M2I Deposit","ICICI Ngl NRE"),
            Map.entry("ICICI NRE A/c - Credit","ICICI Ngl NRE"),
            Map.entry("ICICI NRE A/c - Debit Card","Other Expense"),
            Map.entry("Tambaram Apt - Bank Saving","Canara Bank Guindy"),
            Map.entry("ICICI NRE A/c - Tambaram Apt Maintanence","Other Expense"),
            Map.entry("CEFCU Checking A/c [S] - Check Payment","Housing Expenses"),
            Map.entry("Mama Cash Payment","Other Expense"),
            Map.entry("CEFCU Savings A/c [S] -> Checking A/c [S]","CEFCU Checking - Sebina"),
            Map.entry("SBI NRE A/c - Internet Payment","Other Expense"),
            Map.entry("Sodexo","Other Expense"),
            Map.entry("ICICI NRE A/c - Withdraw","CashAsset"),
            Map.entry("ICICI Cat Salary A/c [D] - Credit","ICICI Thoraipakkam - Dinesh"),
            Map.entry("ICICI Cat Salary A/c [S] - Credit","ICICI Thoraipakkam - Sebina"),
            Map.entry("ICICI Cat Salary A/c [D] - Withdraw","CashAsset"),
            Map.entry("ICICI Res A/c ->ICICI Cat Sal A/c [D]","ICICI Thoraipakkam - Dinesh"),
            Map.entry("Dinesh - ICICI Perungudi Savings","Other Expense"),
            Map.entry("SBI Advantage Credit Card [D]","Other Expense"),
            Map.entry("SBI Advantage Credit Card [S]","Other Expense"),
            Map.entry("ICICI Cat Salary A/c [S] - Check Payment","Other Expense"),
            Map.entry("Sebi - ICICI Perungudi Savings","Other Expense"),
            Map.entry("ICICI Cat Salary A/c [S] - Cash Withdraw","CashAsset"),
            Map.entry("Cash Lend","Personal Loan"),
            Map.entry("ICICI Cat Salary A/c [D] -> ICICI Res A/c ","ICICI Ngl Joint"),
            Map.entry("SBI Perungudi A/c [D] - Credit","ICICI Thoraipakkam - Dinesh"),
            Map.entry("ICICI NRE A/c ->ICICI Cat Sal A/c [D]","ICICI Thoraipakkam - Dinesh"),
            Map.entry("ICICI NRE A/c ->ICICI Cat Sal A/c [S]","ICICI Thoraipakkam - Sebina"),
            Map.entry("SBI NRE A/c -> SBI Velachery A/c [D]","SBI Perungudi - Dinesh"),
            Map.entry("SBI Perungudi A/c [D] - Withdraw","CashAsset"),
            Map.entry("SBI Perungudi A/c [D] - Check Payment","Other Expense"),
            Map.entry("SBI Perungudi A/c [D] - Debit Card","Other Expense"),
            Map.entry("SBI Perungudi A/c [S] - Credit","SBI Perungudi - Sebina"),
            Map.entry("ICICI Cat Salary A/c [S] -> ICICI Cat Salary A/c [D]","ICICI Thoraipakkam - Dinesh"),
            Map.entry("ICICI Cat Salary A/c [D] - Check Payment","Other Expense"),
            Map.entry("HSBC Home Loan - Debit","Other Expense"),
            Map.entry("ICICI Cat Salary A/c [D] -> HSBC Home Loan","HSBC Home Loan"),
            Map.entry("Cash Lend Refund","CashAsset"),
            Map.entry("ICICI Cat Salary A/c [D] -> SBI Perungudi A/c [D]","SBI Perungudi - Dinesh"),
            Map.entry("ICICI Cat Salary A/c [S] -> SBI Perungudi A/c [S]","SBI Perungudi - Sebina"),
            Map.entry("For Records","Other Expense"),
            Map.entry("SBI Perungudi A/c [D] -> ICICI Cat Salary A/c [D] ","ICICI Thoraipakkam - Dinesh"),
            Map.entry("ICICI Res A/c ->ICICI Cat Sal A/c [S]","ICICI Thoraipakkam - Sebina"),
            Map.entry("Canara Bank Adyar A/c [D] - Credit","Canara Bank Adyar"),
            Map.entry("SBI Perungudi A/c [D] -> HSBC Home Loan","HSBC Home Loan"),
            Map.entry("Rams Dwaraka Income","CashAsset"),
            Map.entry("Rams Dwaraka Expense","Other Expense"),
            Map.entry("HSBC Credit Card [D]","Other Expense"),
            Map.entry("Sebi - HSBC","Other Expense"),
            Map.entry("Canara Bank Adyar A/c [D] - Debit Card","Other Expense"),
            Map.entry("Dinesh - SBI GM","Other Expense"),
            Map.entry("ICICI Cat Salary A/c [D] -> ICICI Cat Salary A/c [S]","ICICI Thoraipakkam - Sebina"),
            Map.entry("HSBC Home Loan -> ICICI Cat Salary A/c [S]","ICICI Thoraipakkam - Sebina"),
            Map.entry("HSBC Home Loan -> ICICI Cat Salary A/c [D]","ICICI Thoraipakkam - Dinesh"),
            Map.entry("Dinesh - AMEX","Other Expense"),
            Map.entry("Cash - $","Other Expense"),
            Map.entry("Dinesh - HDFC Savings A/c","Other Expense"));
}
