package com.home.expensetrack.datamigrate.mapper.Impl;

import java.util.Map;

public class Map2015TypeTo2024CreditSubAccounts {

    public static Map<String, String> map = Map.ofEntries(Map.entry("CASH - $","Cash"),
            Map.entry("CEFCU Checking A/c [D] - Check Payment","CEFCU Checking - Dinesh"),
            Map.entry("Shell Charge Card","Shell Charge Card"),
            Map.entry("CEFCU Credit Card [D]","CEFCU - Dinesh"),
            Map.entry("CEFCU Debit Card [D] - Payment","CEFCU Checking - Dinesh"),
            Map.entry("CEFCU Checking A/c [D] - Withdraw","CEFCU Checking - Dinesh"),
            Map.entry("Lend Cash","Cash"),
            Map.entry("CEFCU Checking A/c [D] - Check Deposit","Vendor Bank"),
            Map.entry("CEFCU Checking A/c [D] - ACH Payment","CEFCU Checking - Dinesh"),
            Map.entry("CEFCU Checking A/c [D] -> Savings A/c [D]","CEFCU Checking - Dinesh"),
            Map.entry("CEFCU Checking A/c [D] - ACH Deposit","Caterpillar Inc"),
            Map.entry("Cash Received","Vendor Cash"),
            Map.entry("Bergner's Card [D]","Bergners Card"),
            Map.entry("CEFCU Checking A/c [D] - Credit Card Check Payment","CEFCU Checking - Dinesh"),
            Map.entry("JCPenney Card","JCPenney Card"),
            Map.entry("Paid for with CEFCU Credit Card","CEFCU - Dinesh"),
            Map.entry("Chase Credit Card","Chase Card"),
            Map.entry("Sears Charge Card","Sears Charge Card"),
            Map.entry("Cash - INR","Cash"),
            Map.entry("CEFCU Checking A/c [D] - Credit Card ACH Payment","CEFCU Checking - Dinesh"),
            Map.entry("Famous Baar / Macy's Card","Famous Baar - Macys Card"),
            Map.entry("Online Payment - CEFCU","CEFCU Checking - Dinesh"),
            Map.entry("CEFCU Checking A/c [D] - M2I Transfer","CEFCU Checking - Dinesh"),
            Map.entry("Kohl's Card [D] & [S]","Kohls Card"),
            Map.entry("Providian CreditCard Deposit","Vendor Bank"),
            Map.entry("Mail In Rebate - Checks","Vendor Bank"),
            Map.entry("Gift Card - Received","Vendor Cash"),
            Map.entry("Gift Card - Payment","Gift Card"),
            Map.entry("Refund","Vendor Cash"),
            Map.entry("CEFCU Debit Card [D] - Withdraw","CEFCU Checking - Dinesh"),
            Map.entry("Sears Master Card","Sears Master Card"),
            Map.entry("Sam's Club Discover Card","Sams Club Discover Card"),
            Map.entry("CEFCU Checking A/c [S] - Check Deposit","Caterpillar Inc"),
            Map.entry("CAT Health Insurance - Payment","Caterpillar Inc"),
            Map.entry("CEFCU Saving A/c [S] -> Checking A/c [D]","CEFCU Saving - Sebina"),
            Map.entry("CEFCU Saving A/c [S] - Check Deposit","Caterpillar Inc"),
            Map.entry("CEFCU Checking A/c [S] - ACH Deposit","Caterpillar Inc"),
            Map.entry("CEFCU Check Card [S] - Payment","CEFCU Checking - Sebina"),
            Map.entry("CEFCU Checking A/c [S] - Withdraw","CEFCU Checking - Sebina"),
            Map.entry("ICICI Res A/c - M2I Deposit","CEFCU"),
            Map.entry("CEFCU Saving A/c [S] - ACH Deposit","CEFCU"),
            Map.entry("CEFCU Saving A/c [D] - ACH Deposit","CEFCU"),
            Map.entry("CEFCU Checking A/c [S] -> Savings A/c [S]","CEFCU Checking - Sebina"),
            Map.entry("CEFCU Savings A/c [D] -> Checking A/c [D]","CEFCU Saving - Dinesh"),
            Map.entry("Bergner's Card [S]","Bergners Card"),
            Map.entry("SBI Remit Express Transfer","CEFCU Checking - Dinesh"),
            Map.entry("CEFCU Saving A/c [D] - Check Deposit","Other Bank"),
            Map.entry("Joint ICICI NGL Savings A/c","ICICI Ngl Joint"),
            Map.entry("CEFCU Checking A/c [S] -> Checking A/c [D]","CEFCU Checking - Sebina"),
            Map.entry("CEFCU Checking A/c [D] - SBI Remit Express","CEFCU Checking - Dinesh"),
            Map.entry("ICICI Res A/c - Credit","ICICI"),
            Map.entry("CEFCU Saving A/c [S] -> Saving A/c [D]","CEFCU Saving - Sebina"),
            Map.entry("Tambaram Project - Cash Payment","Cash"),
            Map.entry("Tambaram Project - Mama Cash Payment","Cash"),
            Map.entry("CEFCU Saving A/c [S] -> Santa Saver A/c [S]","CEFCU Saving - Sebina"),
            Map.entry("ICICI Res A/c - Tambaram Project Payment","ICICI Ngl Joint"),
            Map.entry("CEFCU Checking A/c [S] -> Savings A/c [D]","CEFCU Checking - Sebina"),
            Map.entry("ICICI Res A/c - Withdraw","ICICI Ngl Joint"),
            Map.entry("SBI NRE A/c - Credit","Other Bank"),
            Map.entry("Cash Received - Rs","Vendor Cash"),
            Map.entry("Tambaram Apt - Maintanence","Cash"),
            Map.entry("Tambaram Apt - Rent","Tenant"),
            Map.entry("ICICI Res A/c - Tambaram Apt Maintanence","ICICI Ngl Joint"),
            Map.entry("SBI NRE A/c - Check Payment","SBI Kulithurai NRE"),
            Map.entry("ICICI NRE A/c - M2I Deposit","CEFCU"),
            Map.entry("ICICI NRE A/c - Credit","Other Bank"),
            Map.entry("ICICI NRE A/c - Debit Card","ICICI Ngl NRE"),
            Map.entry("Tambaram Apt - Bank Saving","Cash"),
            Map.entry("ICICI NRE A/c - Tambaram Apt Maintanence","ICICI Ngl NRE"),
            Map.entry("CEFCU Checking A/c [S] - Check Payment","CEFCU Checking - Sebina"),
            Map.entry("Mama Cash Payment","Cash"),
            Map.entry("CEFCU Savings A/c [S] -> Checking A/c [S]","CEFCU Saving - Sebina"),
            Map.entry("SBI NRE A/c - Internet Payment","SBI Kulithurai NRE"),
            Map.entry("Sodexo","Sodexo"),
            Map.entry("ICICI NRE A/c - Withdraw","ICICI Ngl NRE"),
            Map.entry("ICICI Cat Salary A/c [D] - Credit","Caterpillar India"),
            Map.entry("ICICI Cat Salary A/c [S] - Credit","Caterpillar India"),
            Map.entry("ICICI Cat Salary A/c [D] - Withdraw","ICICI Thoraipakkam - Dinesh"),
            Map.entry("ICICI Res A/c ->ICICI Cat Sal A/c [D]","ICICI Ngl Joint"),
            Map.entry("Dinesh - ICICI Perungudi Savings","ICICI Thoraipakkam - Dinesh"),
            Map.entry("SBI Advantage Credit Card [D]","SBI Advantage - Dinesh"),
            Map.entry("SBI Advantage Credit Card [S]","SBI Advantage - Sebina"),
            Map.entry("ICICI Cat Salary A/c [S] - Check Payment","ICICI Thoraipakkam - Dinesh"),
            Map.entry("Sebi - ICICI Perungudi Savings","ICICI Thoraipakkam - Sebina"),
            Map.entry("ICICI Cat Salary A/c [S] - Cash Withdraw","ICICI Thoraipakkam - Dinesh"),
            Map.entry("Cash Lend","Cash"),
            Map.entry("ICICI Cat Salary A/c [D] -> ICICI Res A/c","ICICI Thoraipakkam - Dinesh"),
            Map.entry("SBI Perungudi A/c [D] - Credit","Other Bank"),
            Map.entry("ICICI NRE A/c ->ICICI Cat Sal A/c [D]","ICICI Ngl NRE"),
            Map.entry("ICICI NRE A/c ->ICICI Cat Sal A/c [S]","ICICI Ngl NRE"),
            Map.entry("SBI NRE A/c -> SBI Velachery A/c [D]","SBI Kulithurai NRE"),
            Map.entry("SBI Perungudi A/c [D] - Withdraw","SBI Perungudi - Dinesh"),
            Map.entry("SBI Perungudi A/c [D] - Check Payment","SBI Perungudi - Dinesh"),
            Map.entry("SBI Perungudi A/c [D] - Debit Card","SBI Perungudi - Dinesh"),
            Map.entry("SBI Perungudi A/c [S] - Credit","Other Bank"),
            Map.entry("ICICI Cat Salary A/c [S] -> ICICI Cat Salary A/c [D]","ICICI Thoraipakkam - Sebina"),
            Map.entry("ICICI Cat Salary A/c [D] - Check Payment","ICICI Thoraipakkam - Dinesh"),
            Map.entry("HSBC Home Loan - Debit","HSBC Home Loan"),
            Map.entry("ICICI Cat Salary A/c [D] -> HSBC Home Loan","ICICI Thoraipakkam - Dinesh"),
            Map.entry("Cash Lend Refund","Personal Loan"),
            Map.entry("ICICI Cat Salary A/c [D] -> SBI Perungudi A/c [D]","ICICI Thoraipakkam - Dinesh"),
            Map.entry("ICICI Cat Salary A/c [S] -> SBI Perungudi A/c [S]","ICICI Thoraipakkam - Sebina"),
            Map.entry("For Records","Cash"),
            Map.entry("SBI Perungudi A/c [D] -> ICICI Cat Salary A/c [D]","SBI Perungudi - Dinesh"),
            Map.entry("ICICI Res A/c ->ICICI Cat Sal A/c [S]","ICICI Ngl Joint"),
            Map.entry("Canara Bank Adyar A/c [D] - Credit","Cash"),
            Map.entry("SBI Perungudi A/c [D] -> HSBC Home Loan","SBI Perungudi - Dinesh"),
            Map.entry("Rams Dwaraka Income","Vendor Cash"),
            Map.entry("Rams Dwaraka Expense","Cash"),
            Map.entry("HSBC Credit Card [D]","HSBC - Dinesh"),
            Map.entry("Sebi - HSBC","HSBC - Sebina"),
            Map.entry("Canara Bank Adyar A/c [D] - Debit Card","Canara Bank Adyar"),
            Map.entry("Dinesh - SBI GM","SBI GM - Dinesh"),
            Map.entry("ICICI Cat Salary A/c [D] -> ICICI Cat Salary A/c [S]","ICICI Thoraipakkam - Dinesh"),
            Map.entry("HSBC Home Loan -> ICICI Cat Salary A/c [S]","HSBC Home Loan"),
            Map.entry("HSBC Home Loan -> ICICI Cat Salary A/c [D]","HSBC Home Loan"),
            Map.entry("Dinesh - AMEX","Amex - Dinesh"),
            Map.entry("Cash - $","Cash"),
            Map.entry("Dinesh - HDFC Savings A/c","HSBC Perungudi - Dinesh"));
}
